### ISSUE TITLE
Sending a link to the story book crash

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#188]
I just wanted to share this link

https://zakodium.github.io/react-plot/?path=/story/api-scatter--scatter-control

But I get an error

```
values is not iterable
TypeError: values is not iterable
    at __webpack_exports__.a (https://zakodium.github.io/react-plot/vendors~main.b02a85c3.iframe.bundle.js:2:1917008)
    at https://zakodium.github.io/react-plot/main.d4c7e6f4.iframe.bundle.js:1:326405
    at fk (https://zakodium.github.io/react-plot/vendors~main.b02a85c3.iframe.bundle.js:2:1531244)
    at exports.unstable_runWithPriority (https://zakodium.github.io/react-plot/vendors~main.b02a85c3.iframe.bundle.js:2:1549315)
    at gg (https://zakodium.github.io/react-plot/vendors~main.b02a85c3.iframe.bundle.js:2:1471787)
    at Oj (https://zakodium.github.io/react-plot/vendors~main.b02a85c3.iframe.bundle.js:2:1530710)
    at https://zakodium.github.io/react-plot/vendors~main.b02a85c3.iframe.bundle.js:2:1530623
    at V (https://zakodium.github.io/react-plot/vendors~main.b02a85c3.iframe.bundle.js:2:1548285)
    at MessagePort.F.port1.onmessage (https://zakodium.github.io/react-plot/vendors~main.b02a85c3.iframe.bundle.js:2:1546996)
    ```

**Comment by maasencioh** [comment]
seems strange to me, in local I don't have that error on that view, I'll investigate a little bit further
